### PR TITLE
fix(jest): Allow being used inside Jest beforeAll

### LINKED ISSUE #72: Allow being used inside Jest beforeAll
Hello, we are trying to ugprade jest to latest and encounter issue in our upgrade branch with `consol-fail-test`: https://github.com/pass-culture/pass-culture-app-native/pull/3271

example: 
```
  ● Test suite failed to run

    Cannot add a hook after tests have started running. Hooks must be defined synchronously.

      30 |
      31 | global.beforeAll((done) => {
    > 32 |   consoleFailTestModule.cft({
         |                         ^
      33 |     testFramework: 'jest',
      34 |     spyLibrary: 'jest',
      35 |     console: allowConsoleRuntimeConfig,

      at eventHandler (node_modules/jest-circus/build/eventHandler.js:113:11)
      at Object.after (node_modules/console-fail-test/src/environments/jest.js:10:13)
      at Object.<anonymous>.exports.cft (node_modules/console-fail-test/src/cft.js:20:21)
      at Object.cft (src/tests/setupTests.js:32:25)

```
It seems it does not support the latest jest version, is there a workaroud to keep using console-fail-test or a way we can help?

### PR DESCRIPTION
**Pull request by kopax-polyconseil**
Fix #72

### CODE REVIEW

File: src/environments/jest.ts [hunk 1]
```diff
@@ -12,19 +12,27 @@ export const getJestEnvironment: TestEnvironmentGetter = () => {
   ) {
     return undefined;
   }
+  let afterEachCallback = () => {};
+  let beforeEachCallback = () => {};
```
Comment (JoshuaKGoldberg) [inline src/environments/jest.ts:16]: Hmm, looks like CI isn't running on this repo. I'll get it set back up.

```suggestion

  /* eslint-disable @typescript-eslint/no-empty-function */
  let afterEachCallback = () => {};
  let beforeEachCallback = () => {};
  /* eslint-enable @typescript-eslint/no-empty-function */
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, thanks so much for this @kopax-polyconseil! 🎉 

I tested this out locally and it seems to work in all the situations that previously worked. Though, adding a `beforeAll(() => { cft(); }` in a test file or `setupTests.js` still fails for me with this setup. If you moved the `(after|before)EachCallback = () => {};` and `(after|before)Each(() => ...` lines to _outside_ `getJestEnvironment` -and changed the latter to only call if the function is defined- that does fix it. 🤷 if it works for you as-is in this PR, then great!

**Comment by JoshuaKGoldberg** [comment]
Ah, and I no longer have access to publish this package (it used to be under Codecademy) -- will work on that behind the scenes with @jakemhiller.

**Comment by JoshuaKGoldberg** [comment]
Update: this should be published as console-fail-test@0.1.6. Thanks @jakemhiller!
